import type { AppSettings, AppWorkBlock, WorkCategory } from './app-types'

export const APP_VERSION = '0.1.0'

export const DEFAULT_CATEGORIES: readonly WorkCategory[] = [
  { id: 'practice', name: 'Praktische Ausbildung', color: '#b4232d', icon: 'steering-wheel', active: true, sortOrder: 0, rate: 30 },
  { id: 'theory', name: 'Theorieunterricht', color: '#365b86', icon: 'presentation', active: true, sortOrder: 1, rate: 35 },
  { id: 'exam', name: 'Prüfung', color: '#84553d', icon: 'clipboard-check', active: true, sortOrder: 2 },
  { id: 'office', name: 'Büro & Verwaltung', color: '#527064', icon: 'briefcase', active: true, sortOrder: 3, rate: 25 },
  { id: 'briefing', name: 'Einweisung', color: '#a96c32', icon: 'route', active: true, sortOrder: 4 },
  { id: 'training', name: 'Weiterbildung', color: '#725a9c', icon: 'graduation-cap', active: true, sortOrder: 5 },
  { id: 'other', name: 'Sonstige Tätigkeit', color: '#6d6b68', icon: 'shapes', active: true, sortOrder: 6 },
]

export const DEFAULT_SETTINGS: AppSettings = {
  pay: {
    model: 'time-hour',
    standardRate: 30,
    rounding: 'exact',
    categoryRates: Object.fromEntries(
      DEFAULT_CATEGORIES.filter((category) => category.rate !== undefined).map((category) => [category.id, category.rate!]),
    ),
  },
  currency: 'EUR',
  defaultBreakMinutes: 0,
  defaultCategoryId: 'practice',
  minuteStep: 5,
  overnightAllocation: 'start-date',
  defaultStartTime: '08:00',
  defaultEndTime: '09:30',
  displayMode: 'clock-training',
  weekStartsMonday: true,
  use24Hour: true,
  theme: 'system',
  compactCalendar: true,
  calendar: {
    titleTemplate: 'Fahrschule – {tätigkeit}',
    descriptionTemplate: '{arbeitszeit} · {ausbstunden}',
    color: 'red',
    automatic: false,
    updateAutomatically: false,
    deleteAutomatically: false,
    includeEarnings: true,
  },
  showSampleData: true,
}

export function createSampleBlocks(month: string): readonly AppWorkBlock[] {
  const now = new Date().toISOString()
  return [
    {
      id: 'sample-1',
      date: `${month}-03`,
      startTime: '07:45',
      endTime: '12:30',
      breaks: [{ id: 'sample-break-1', kind: 'duration', minutes: 15 }],
      categoryId: 'practice',
      isPaid: true,
      vehicleClass: 'B',
      studentOrAssignment: 'Beispieltermin',
      notes: 'Beispieldaten – jederzeit in den Einstellungen ausblendbar.',
      location: 'Fahrschule',
      createdAt: now,
      updatedAt: now,
      sample: true,
      syncState: 'synced',
      calendarEventId: 'sample-calendar-1',
    },
    {
      id: 'sample-2',
      date: `${month}-08`,
      startTime: '18:00',
      endTime: '20:15',
      breaks: [],
      categoryId: 'theory',
      isPaid: true,
      activity: 'Grundstoff Klasse B',
      location: 'Unterrichtsraum',
      createdAt: now,
      updatedAt: now,
      sample: true,
      syncState: 'pending',
    },
    {
      id: 'sample-3',
      date: `${month}-15`,
      startTime: '08:00',
      endTime: '12:15',
      breaks: [{ id: 'sample-break-2', kind: 'interval', startTime: '10:00', endTime: '10:15' }],
      categoryId: 'practice',
      isPaid: true,
      vehicleClass: 'B',
      activity: 'Praktische Ausbildung',
      createdAt: now,
      updatedAt: now,
      sample: true,
      syncState: 'pending',
    },
    {
      id: 'sample-4',
      date: `${month}-15`,
      startTime: '21:30',
      endTime: '00:15',
      breaks: [],
      categoryId: 'practice',
      isPaid: true,
      vehicleClass: 'B',
      activity: 'Nachtfahrt',
      rateOverride: 35,
      createdAt: now,
      updatedAt: now,
      sample: true,
      syncState: 'changed',
    },
    {
      id: 'sample-5',
      date: `${month}-18`,
      startTime: '09:00',
      endTime: '10:30',
      breaks: [],
      categoryId: 'exam',
      isPaid: true,
      vehicleClass: 'BE',
      createdAt: now,
      updatedAt: now,
      sample: true,
      syncState: 'pending',
    },
  ]
}
